### ISSUE TITLE
请问为什么heads添加了X-s和X-t字段还是不可以正确请求接口呢

### ISSUE THREAD

**Issue by Nomination-NRB** [wang-zhiyang/xhscrawl#4]
代码：
![image](https://github.com/wang-zhiyang/xhscrawl/assets/83486284/a11e71d9-7390-489b-ac07-92c1ec356453)

输出结果：
![image](https://github.com/wang-zhiyang/xhscrawl/assets/83486284/414cbcf3-dea7-4bfa-ba5b-3b100fd997a8)

**Comment by wang-zhiyang** [comment]
你的url不对呀，你用api=“comment/post” 生成的x-s，去请求comment/page接口当然不行了
